spring:
  application:
    name: Fast-delivery

  cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT}
    local-datacenter: ${CASSANDRA_DATACENTER}
    keyspace-name: ${CASSANDRA_KEYSPACE}
    schema-action: NONE

server:
  port: ${SERVER_PORT}

osrm:
  base-url: ${OSRM_BASE_URL}

nominatim:
  search-url: ${NOMINATIM_SEARCH_URL}